### ISSUE TITLE
Error: lookup 127-0-0-1-reads-thenaritiv-lcl.lcl.host: no such host

### ISSUE THREAD

**Issue by moraar222** [anchordotdev/cli#44] opened 2024-11-05 23:18 UTC
**Are there any additional details you would like to share?**

---

**Command:** `anchor lcl`
**Executable:** `C:\Program Files\Anchor CLI\anchor.exe`
**Version:** `0.1.6 (windows/amd64) Commit: 3d6f32576ae7aaf17172ec968bb44012aa0d4753 BuildDate: 2024-10-30T16:24:30Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-11-05T23:17:19.3774557Z`
**Stdout:**
```
| Let's set up fast and totally free lcl.host HTTPS!
                                                                 
# Setup lcl.host HTTPS Local Development Environment `anchor lcl`
    | We'll set you up to use HTTPS locally in your browsers and other programs.
                                                                       
# Audit lcl.host HTTPS Local Development Environment `anchor lcl audit`
    | We'll compare your local development CA certificates from Anchor and your local trust stores.
    - Compared local and expected CA certificates: need to install 2 missing certificates.
                                                                                          
# Initial System Configuration for lcl.host Local HTTPS Development `anchor lcl bootstrap`
    | We'll configure your browsers and OS to trust your local development certificates.
    - Checked diagnostic service on Anchor.dev: need to provision service.
    - Entered hi-moraar222.lcl.host domain for lcl.host diagnostic certificate.
    - Resolved hi-moraar222.lcl.host domain: failed!
    | The entered domain name is either invalid or cannot be resolved from
    | your machine, possibly due to rebinding protection on your DNS server.
    | Learn more here: https://lcl.host/dns-rebinding
                                               
# Setup lcl.host Application `anchor lcl setup`
    | We'll integrate your application and system for HTTPS local development.
    - Using moraar222, the only available organization. You can also use `--org moraar222`.
    - Using localhost, the only available realm. You can also use `--realm localhost`.
    - No services found, so we'll create one.
    - Scanned current directory.
    - Entered javascript application server type.
    - Entered 127.0.0.1 reads-thenaritiv-lcl application name.
    - Entered 127-0-0-1-reads-thenaritiv-lcl.lcl.host domain for local application development.
    * Resolving 127-0-0-1-reads-thenaritiv-lcl.lcl.host domain…⠋
```

**Comment by geemus** [comment] 2024-11-06 17:34
Going to close this as a duplicate of #43 (I'll respond in more depth there).

**Closed** 2024-11-06 17:34 UTC
