### ISSUE TITLE
Error: lookup hi-amenu-sh.lcl.host: no such host

### ISSUE THREAD

**Issue by Amenu-sh** [anchordotdev/cli#20] opened 2024-06-24 13:35 UTC
**Are there any additional details you would like to share?**

---

**Command:** `anchor lcl`
**Executable:** `/opt/homebrew/bin/anchor`
**Version:** `0.0.37 (darwin/arm64) Commit: 1cd0aa11dbb338760b0ff26abf1f469d6ae5b1a9 BuildDate: 2024-05-28T21:30:13Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-06-24T13:35:13.211008Z`
**Stdout:**
```
| Let's set up lcl.host HTTPS in your local development environment!
| 
| lcl.host (made by the team at Anchor) adds HTTPS in a fast and totally free way
| to local applications & services.
# Setup lcl.host HTTPS Local Development Environment `anchor lcl`
    | Once setup finishes, you'll have a secure context in your browsers and local
    | system so you can use HTTPS locally.
# Audit lcl.host HTTPS Local Development Environment `anchor lcl audit`
    | We'll begin by checking your system to determine what you need for your setup.
    - Checked resources on Anchor.dev: need to provision resources.
    - Compared local and expected CA certificates: need to install 2 missing certificates.
# Configure System for lcl.host HTTPS Local Development `anchor lcl config`
    | Before issuing HTTPS certificates for your local applications, we need to
    | configure your browsers and OS to trust your personal certificates.
    |
    | We'll start a local diagnostic web server to guide you through the process.
    - Entered hi-amenu-sh.lcl.host domain for lcl.host diagnostic certificate.
    - Resolved hi-amenu-sh.lcl.host domain: failed!
    | The entered domain name is either invalid or cannot be resolved from
    | your machine, possibly due to rebinding protection on your DNS server.
    | Learn more here: https://lcl.host/dns-rebinding
```

**Comment by geemus** [comment] 2024-06-24 14:07
Closing as duplicate of #19 (I'll dig in and provide more details/feedback there as I'm able)

**Closed by geemus** 2024-06-24 14:07 UTC
