### ISSUE TITLE
Error: request [9ea233ef-dc10-442d-849e-f3f3b0e6bec5]: unexpected 400 status response: Invalid domain: testing.localhost

### ISSUE THREAD

**Issue by danbernier** [anchordotdev/cli#26] opened 2024-07-08 16:49 UTC
**Are there any additional details you would like to share?**

Interesting; I'm not sure what the root cause is here.

---

**Command:** `anchor lcl`
**Executable:** `/opt/homebrew/bin/anchor`
**Version:** `0.0.38 (darwin/arm64) Commit: 38a58bce9066abd76402b4acf560bfce5c03ec94 BuildDate: 2024-06-25T19:20:28Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-07-08T16:48:50.600203Z`
**Stdout:**
```
| Let's set up fast and totally free lcl.host HTTPS!
# Setup lcl.host HTTPS Local Development Environment `anchor lcl`
    | After setup, you can use HTTPS locally in your browsers and other programs.
# Audit lcl.host HTTPS Local Development Environment `anchor lcl audit`
    | We'll begin by checking your system to determine what you need for your setup.
    - Checked resources on Anchor.dev: no provisioning needed.
    - Compared local and expected CA certificates: need to install 2 missing certificates.
# Configure System for lcl.host HTTPS Local Development `anchor lcl config`
    | Before issuing HTTPS certificates, we need to configure your browsers
    | and OS to trust your personal certificates.
    |
    | We'll start a local diagnostic web server to guide you through the process.
    - Entered hi-danbernier.lcl.host domain for lcl.host diagnostic certificate.
    - Resolved hi-danbernier.lcl.host domain: success!
    | Now we'll provision Anchor.dev resources and HTTPS certificates for you.
    - Created hi-danbernier [hi-danbernier.lcl.host, hi-danbernier.localhost] diagnostic resources on Anchor.dev.
    - Great, http://hi-danbernier.lcl.host:4433 works as expected (without HTTPS).
    | Next, we'll add your personal CA certificates to your system's trust stores.
# Manage CA Certificates in your Local Trust Store(s) `anchor trust`
    - Compared local and expected CA certificates: need to install 2 missing certificates.
    - Updated System (MacOS Keychain): installed danbernier/localhost - AnchorCA [ECDSA, RSA]
    - Updated Network Security Services (NSS): installed danbernier/localhost - AnchorCA [ECDSA, RSA]
    - Updated Homebrew OpenSSL (ca-certificates): installed danbernier/localhost - AnchorCA [ECDSA, RSA]
    | Before we move on, let's test HTTPS.
    - Success! https://hi-danbernier.lcl.host:4433 works as expected (encrypted with HTTPS).
# Setup lcl.host Application `anchor lcl setup`
    | We'll gather details from you and your system to customize setup instructions.
    - Scanned current directory.
    - Entered ruby application server type.
    - Entered testing application name.
    - Entered testing.lcl.host domain for local application development.
    - Resolved testing.lcl.host domain: success!
    | Now we'll provision Anchor.dev resources and HTTPS certificates for you.
    - Creating testing [testing.lcl.host, testing.localhost] ruby resources on Anchor.dev… ⠋
```

**Comment by geemus** [comment] 2024-07-16 13:23
Yeah, did you have any further luck reproducing this? I was unable to myself.

**Comment by geemus** [comment] 2024-09-16 14:45
Closing this as we have been unable to reproduce, but just let us know if we assist.

**Closed by geemus** 2024-09-16 14:45 UTC
