### ISSUE TITLE
Error: acme/autocert: certificate is not valid yet

### ISSUE THREAD

**Issue by mekkaouiabdessamad0** [anchordotdev/cli#25] opened 2024-06-29 11:51 UTC
**Are there any additional details you would like to share?**

---

**Command:** `anchor lcl`
**Executable:** `C:\Program Files\Anchor CLI\anchor.exe`
**Version:** `0.0.38 (windows/amd64) Commit: 38a58bce9066abd76402b4acf560bfce5c03ec94 BuildDate: 2024-06-25T19:20:43Z`
**Arguments:** `[]`
**Flags:** `[]`
**Timestamp:** `2024-06-29T11:50:31.8727193Z`
**Stdout:**
```
| Let's set up fast and totally free lcl.host HTTPS!
# Setup lcl.host HTTPS Local Development Environment `anchor lcl`
    | After setup, you can use HTTPS locally in your browsers and other programs.
# Audit lcl.host HTTPS Local Development Environment `anchor lcl audit`
    | We'll begin by checking your system to determine what you need for your setup.
    - Checked resources on Anchor.dev: no provisioning needed.
    - Compared local and expected CA certificates: need to install 2 missing certificates.
# Configure System for lcl.host HTTPS Local Development `anchor lcl config`
    | Before issuing HTTPS certificates, we need to configure your browsers
    | and OS to trust your personal certificates.
    |
    | We'll start a local diagnostic web server to guide you through the process.
    - Entered hi-mekkaouiabdessamad0.lcl.host domain for lcl.host diagnostic certificate.
    - Resolved hi-mekkaouiabdessamad0.lcl.host domain: success!
    | Now we'll provision Anchor.dev resources and HTTPS certificates for you.
    - Creating hi-mekkaouiabdessamad0 [hi-mekkaouiabdessamad0.lcl.host, hi-mekkaouiabdessamad0.localhost] diagnostic resources on Anchor.dev… ⠋
```

**Comment by geemus** [comment] 2024-06-29 13:03
Closing as a duplicate of #24 (I'll reply in more detail there).

**Closed by geemus** 2024-06-29 13:03 UTC
